### setup
configfile: "config.yaml"

# include: "rules/download.smk"

## Query ENA for datasets
batchOverviewFile = config['outFile'] + '_batches.list'

rule query_ena:
    """
    Query ENA for metagenomic datasets, update database, and make files with ascp commands for download
    """
    params:
        baseDir=config['baseDir'],
        fromDate=config['from_date'],
        toDate=config['to_date'],
        batchSize=config['batchSize'],
        outFile=config['outFile']
    output:
        batchOverviewFile ### TODO: fails here?
    log: "logs/ena_query.log"
    message: "Retrieving metadata and run_accessions from ENA"
    conda: "environment.yaml"
    shell:
        """
        python ../../scripts/ENA_fetcher.py -d {params.fromDate} -td {params.toDate} -b {params.baseDir} --no-update --no-check_db --out_file {params.outFile} --batch_size {params.batchSize} > {log}
        """

# Goal is to get the list of batches from the previus rule - DOES NOT WORK.
checkpoint get_batches: 
    params:
        outFile=config['outFile']
    shell: """
    ls {params.outFile}*.sh
    """

rule download:
    input: f"{config['outFile']}"
    log: "logs/download.log"
    message: "Downloading raw FASTQ files"
    shell: """
    echo {input}
    """
    # """
    # parallel -j 1 < {input}
    # """