### setup
configfile: "config.yaml"

# include: "rules/download.smk"

## Query ENA for datasets
batchOverviewFile = config['outFile'] + '_batches.list'

rule query_ena:
    """
    Query ENA for metagenomic datasets, update database, and make files with ascp commands for download
    """
    params:
        baseDir=config['baseDir'],
        fromDate=config['from_date'],
        toDate=config['to_date'],
        batchSize=config['batchSize'],
        outFile=config['outFile']
    output:
        batchOverviewFile
    log: "logs/ena_query.log"
    message: "Retrieving metadata and run_accessions from ENA"
    conda: "environment.yaml"
    shell:
        """
        python ../../scripts/ENA_fetcher.py -d {params.fromDate} -td {params.toDate} -b {params.baseDir} --no-update --no-check_db --out_file {params.outFile} --batch_size {params.batchSize} > {log}
        """

# rule download:
#     input: f"{config['outFile']}"
#     log: "logs/download.log"
#     message: "Downloading raw FASTQ files"
#     shell:
#     """
#     parallel -j 1 < {input}
#     """



# for batch in batches:
#     rule download:
#         params: batchcmds = batch
#         log: "logs/download.log"
#         shell: "echo {params.batchFile} > {log}"