name: AvA
channels:
  - conda-forge
  - bioconda
  - default
  - hcc
dependencies:
  - python=3.8.0
  - snakemake
  - tabulate==0.8.10
  - kma==1.4.3
  - fastqc==0.11.9
  - parallel==20211122
  - pip
  - mysql==8.0.28
  - fastqc==0.11.9
  - bbmap==38.18
  - pip:
    - pandas==1.3.5
    - numpy==1.21.2
