### setup
configfile: "config.yaml"

batchOverviewFile = config['outFile'] + '_batches.list'
batches = []
with open(batchOverviewFile) as f:
    for l in f: 
        batches.append(l.strip())

for b in batches:
    rule download:
        input: 
            batch = b
        log: "logs/download.log"
        threads: workflow.cores
        shell: "(parallel -j {threads} < {input}) > {log}" 

    rule get_runs:
        params:
            baseDir=config['baseDir']
        shell:
            """
            find {params.baseDir} -mindepth 2 -type f -name '*.fastq.gz'
            """