cluster: qsub -W group_list={cluster.proj} -A {cluster.proj} -l nodes=1:ppn={cluster.core},mem={cluster.vmem},walltime={cluster.time} -e snakemake.err -o snakemake.log
cluster-config: profile_ava/cluster_computerome.json
use-envmodules: True
restart-times: 2
latency-wait: 200
jobs: 200
keep-going: True
rerun-incomplete: True
